org.gradle.java.home=C\:\\Program Files\\Android\\Android Studio\\jbr
android.useAndroidX=false
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=35

systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7890
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7890
